// <auto-generated />
using System;
using MailDemon;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MailDemon.Migrations
{
    [DbContext(typeof(MailDemonDatabase))]
    partial class MailDemonDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("MailDemon.MailList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Company");

                    b.Property<string>("FromEmailAddress");

                    b.Property<string>("FromEmailName");

                    b.Property<string>("Name");

                    b.Property<string>("PhysicalAddress");

                    b.Property<string>("Title");

                    b.Property<string>("Website");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Lists");
                });

            modelBuilder.Entity("MailDemon.MailListSubscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EmailAddress");

                    b.Property<string>("EmailAddressDomain");

                    b.Property<DateTime>("Expires");

                    b.Property<string>("FieldsJson");

                    b.Property<string>("IPAddress");

                    b.Property<string>("LanguageCode");

                    b.Property<string>("ListName");

                    b.Property<string>("Result");

                    b.Property<DateTime>("ResultTimestamp");

                    b.Property<string>("SubscribeToken");

                    b.Property<DateTime>("SubscribedDate");

                    b.Property<string>("UnsubscribeToken");

                    b.Property<DateTime>("UnsubscribedDate");

                    b.HasKey("Id");

                    b.HasIndex("EmailAddress");

                    b.HasIndex("EmailAddressDomain");

                    b.HasIndex("ListName");

                    b.HasIndex("Result");

                    b.HasIndex("SubscribeToken");

                    b.HasIndex("UnsubscribeToken");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("MailDemon.MailTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Dirty");

                    b.Property<DateTime>("LastModified");

                    b.Property<string>("Name");

                    b.Property<string>("Text");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Templates");
                });
#pragma warning restore 612, 618
        }
    }
}
