//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailDemon {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MailDemon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already subscribed to the &apos;{0}&apos; mailing list..
        /// </summary>
        public static string AlreadySubscribed {
            get {
                return ResourceManager.GetString("AlreadySubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Please confirm your subscription to the &apos;{0}&apos; mailing list by clicking this link:&lt;/p&gt;
        ///&lt;p&gt;&lt;a href=&quot;{1}&quot; target=&quot;_blank&quot;&gt;{1}&lt;/a&gt;&lt;/p&gt;
        ///&lt;p&gt;If you do not click the link, you will not receive emails from the &apos;{0}&apos; mailing list.&lt;/p&gt;.
        /// </summary>
        public static string BodyConfirmSubscription {
            get {
                return ResourceManager.GetString("BodyConfirmSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Welcome to your subscription to the &apos;{0}&apos; mailing list.&lt;/p&gt;
        ///&lt;p&gt;To unsubscribe from this mailing list, please use the following link:&lt;/p&gt;
        ///&lt;p&gt;&lt;a href=&quot;{1}&quot; target=&quot;_blank&quot;&gt;{1}&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        public static string BodyWelcomeSubscription {
            get {
                return ResourceManager.GetString("BodyWelcomeSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit List.
        /// </summary>
        public static string EditList {
            get {
                return ResourceManager.GetString("EditList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Template.
        /// </summary>
        public static string EditTemplate {
            get {
                return ResourceManager.GetString("EditTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is invalid..
        /// </summary>
        public static string EmailIsInvalid {
            get {
                return ResourceManager.GetString("EmailIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by &lt;a target=&apos;_blank&apos; href=&apos;https://github.com/DigitalRuby/MailDemon&apos;&gt;MailDemon&lt;/a&gt;, (c) 2018 &lt;a target=&apos;_blank&apos; href=&apos;https://www.digitalruby.com&apos;&gt;Digital Ruby, LLC&lt;/a&gt;.
        /// </summary>
        public static string FooterText {
            get {
                return ResourceManager.GetString("FooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified.
        /// </summary>
        public static string LastModified {
            get {
                return ResourceManager.GetString("LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Name.
        /// </summary>
        public static string ListName {
            get {
                return ResourceManager.GetString("ListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List &apos;{0}&apos; not found.
        /// </summary>
        public static string ListNotFound {
            get {
                return ResourceManager.GetString("ListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists.
        /// </summary>
        public static string Lists {
            get {
                return ResourceManager.GetString("Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as {0}.
        /// </summary>
        public static string LoggedInAs {
            get {
                return ResourceManager.GetString("LoggedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name may not change.
        /// </summary>
        public static string NameCannotChange {
            get {
                return ResourceManager.GetString("NameCannotChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name, use only letters, numbers, spaces, period, hyphen or underscore..
        /// </summary>
        public static string NameInvalidChars {
            get {
                return ResourceManager.GetString("NameInvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is too long, limit is {0} characters.
        /// </summary>
        public static string NameIsTooLong {
            get {
                return ResourceManager.GetString("NameIsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New List.
        /// </summary>
        public static string NewList {
            get {
                return ResourceManager.GetString("NewList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Template.
        /// </summary>
        public static string NewTemplate {
            get {
                return ResourceManager.GetString("NewTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact support.
        /// </summary>
        public static string PleaseContactSupport {
            get {
                return ResourceManager.GetString("PleaseContactSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your subscription to the &apos;{0}&apos; mailing list.
        /// </summary>
        public static string SubjectConfirmSubscription {
            get {
                return ResourceManager.GetString("SubjectConfirmSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to your subscription to the &apos;{0}&apos; mailing list..
        /// </summary>
        public static string SubjectWelcomeSubscription {
            get {
                return ResourceManager.GetString("SubjectWelcomeSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email for a confirmation link, you should open this link to confirm your subscription to the &apos;{0}&apos; mailing list..
        /// </summary>
        public static string SubscribeConfirm {
            get {
                return ResourceManager.GetString("SubscribeConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error subscribing to the &apos;{0}&apos; mailing list, please contact support..
        /// </summary>
        public static string SubscribeError {
            get {
                return ResourceManager.GetString("SubscribeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to the &apos;{0}&apos; mailing list.
        /// </summary>
        public static string SubscribeText {
            get {
                return ResourceManager.GetString("SubscribeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the &apos;{0}&apos; mailing list. Your subscription is now active. To unsubscribe from this mailing list, please use the following link: .
        /// </summary>
        public static string SubscribeWelcome {
            get {
                return ResourceManager.GetString("SubscribeWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid template name, use only letters, numbers, spaces, period, hyphen or underscore. Format is [listname]{0}[templatename]..
        /// </summary>
        public static string TemplateNameInvalidChars {
            get {
                return ResourceManager.GetString("TemplateNameInvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        public static string Templates {
            get {
                return ResourceManager.GetString("Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has happened, please contact support..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error unsubscribing from the &apos;{0}&apos; mailing list, please contact support..
        /// </summary>
        public static string UnsubscribeError {
            get {
                return ResourceManager.GetString("UnsubscribeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now unsubscribed from the &apos;{0}&apos; mailing list..
        /// </summary>
        public static string UnsubscribeSuccess {
            get {
                return ResourceManager.GetString("UnsubscribeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe from the &apos;{0}&apos; mailing list.
        /// </summary>
        public static string UnsubscribeText {
            get {
                return ResourceManager.GetString("UnsubscribeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is blank.
        /// </summary>
        public static string UsernameOrPasswordIsBlank {
            get {
                return ResourceManager.GetString("UsernameOrPasswordIsBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
